'''
1. SOAP : SIMPLE OBJECT ACCESS PROTOCOL
2.REST : REPRESENTATIONAL STATE TRANSFER
3.GRAPHQL


1)SOAP:
    WSDL (WEB SERVICE DESCRIPTION LANGUAGE)-> XML

2) REST:
    WADL (WEB APPLICATION DESCRIPTION LANGUAGE)->INTILLAY XML CHANGED TO JSON

    URI->UNIFORM RESOURCE IDENTIFIER
    1.IT IS COMBNATION OF 3 THINGS
        BASE URL
        RESOURCE
        PARAMETER(OPTIONAL)

    HTTP METHODS:
        1)GET
        2)POST
        3)PUT (OVER RIDING)
        4)DELETE
'''